version: "3"

services:
  redis:
    image: redis:5
    command: redis-server /etc/redis/redis.conf # 容器启动后启动redis服务器
    volumes:
      - ./compose/redis/data:/data # 通过挂载给redis数据备份
      - ./compose/redis/redis.conf:/etc/redis/redis.conf # 挂载redis配置文件
    expose:
      - 6379
    restart: always # always表容器运行发生错误时一直重启

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456 # 数据库密码
      - MYSQL_DATABASE=backend # 数据库名称
      - MYSQL_USER=dbuser # 数据库用户名
      - MYSQL_PASSWORD=password # 用户密码
    volumes:
      - ./compose/mysql/mysql:/var/lib/mysql:rw # 挂载数据库数据, 可读可写
      - ./compose/mysql/conf/my.cnf:/etc/mysql/my.cnf # 挂载配置文件
      - ./compose/mysql/init:/docker-entrypoint-initdb.d/ # 挂载数据初始化sql脚本
    expose:
      - 3306 # 与配置文件保持一致
    restart: always

  backend:
    build: ./backend
    expose:
      - 8000
    volumes:
      - ./backend:/var/www/html/backend
      - ./compose/uwsgi:/tmp
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    restart: always
    tty: true
    stdin_open: true

  frontend:
    build: ./frontend
    expose:
      - 5000
    command: sh start.sh

  nginx:
    build: ./compose/nginx
    ports:
      - 8000:80
    volumes:
      - ./compose/nginx/conf.d:/etc/nginx/conf.d # 挂载conf.d目录
      - ./compose/nginx/log:/var/log/nginx # 挂载日志
    links:
      - backend
    depends_on:
      - backend
    restart: always
